services:
  traefik:
    image: traefik:v2.6
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "8081:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  backend:
    build: ContainerAppsDemo.Backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`localhost`) && PathPrefix(`/backend`)"
      - "traefik.http.routers.backend.entrypoints=web"
  bff:
    build: ContainerAppsDemo.BackendForFrontend
    links:
      - backend
    environment:
      - BackendBaseUrl=http://backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bff.rule=Host(`localhost`) && PathPrefix(`/bff`)"
      - "traefik.http.routers.bff.entrypoints=web"
  frontend:
    build: ContainerAppsDemo.Frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`localhost`)"
      - "traefik.http.routers.frontend.entrypoints=web"
