
name: Build container images

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "ContainerAppsDemo.Backend/**"

jobs:
  build:
    permissions:
      id-token: write

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Azure ACR Login
      run: |
        az acr login --name acritvinfotag

    - name: Build
      uses: docker/build-push-action@v3
      with:
        context: ContainerAppsDemo.Backend
        tags: acritvinfotag.azurecr.io/containerappsdemo/backend:latest
        push: true

    - name: Build
      uses: docker/build-push-action@v3
      with:
        context: ContainerAppsDemo.BackendForFrontend
        tags: acritvinfotag.azurecr.io/containerappsdemo/bff:latest
        push: true

    - name: Build
      uses: docker/build-push-action@v3
      with:
        context: ContainerAppsDemo.Frontend
        tags: acritvinfotag.azurecr.io/containerappsdemo/frontend:latest
        push: true